name: The Global Missionary
favicon: null
layout_spectrum: 0.99908
typography_spectrum: 0.82402
title: The Global Missionary
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#c2dbf7'
    - '#fecf80'
    - '#33311d'
    - '#c78d42'
  brandStrength: 0.5
  lightness: 0.5
  saturation: 0.5
  rhythmicContrast: 0.5
purpose: []
