name: The Global Missionary
favicon: null
layout_spectrum: 0.6434842569287866
typography_spectrum: 0.82402
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#c2dbf7'
    - '#fecf80'
    - '#33311d'
    - '#c78d42'
  brandStrength: 0.5
  lightness: 0.5
  saturation: 0.5625
  rhythmicContrast: 0.51369219715707
purpose: []
